---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-secret-editor-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-secret-editor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-secret-editor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-secret-editor-role
subjects:
- kind: ServiceAccount
  name: k8s-secret-editor