kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
  name: "k8s-secrets-editor"
  labels:
    state: "serving"
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "k8s-secrets-editor"
        name: "k8s-secrets-editor"
    spec:
      containers:
        - image: bqitdevops/k8s-secret-editor
          imagePullPolicy: Always
          name: k8s-secrets-editor
          ports:
            - containerPort: 80
              name: http
          # Set HTTP admin password. Default admin
          env:
            - name: ADMIN_PASSWORD
              value: 'admin'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: "k8s-secrets-editor"
  name: "k8s-secrets-editor"
spec:
  ports:
    - port: 80
      name: http
  selector:
    name: "k8s-secrets-editor"
